#!/bin/bash
#
# Parses DHCP options from openvpn to update resolv.conf
# To use set as 'up' and 'down' script in your openvpn *.conf:
# up /etc/openvpn/update-resolv-conf
# down /etc/openvpn/update-resolv-conf
#
# Used snippets of resolvconf script by Thomas Hood and Chris Hanson.
# Licensed under the GNU GPL.  See /usr/share/common-licenses/GPL. 
# 
# Example envs set from openvpn:
#
#     foreign_option_1='dhcp-option DNS 193.43.27.132'
#     foreign_option_2='dhcp-option DNS 193.43.27.133'
#     foreign_option_3='dhcp-option DOMAIN be.bnc.ch'
#

#to see the script's debug messages uncomment the next line or add " -x" at the first line
#set -x

scriptDir=$(dirname $0)
. $scriptDir/liny-ovpn-common

resolvConf=$(BinPath resolvconf)
[ -z $resolvConf ] && echo "resolvconf binary not found. It's needed for proper redirecting the dns server to to the one pushed by vpn" && exit 1
[ -z "$script_type" ] && echo "\"script_type\" environment variable not set" && exit 1
[ -z "$dev" ] && echo "\"dev\" environment variable not set" && exit 1

split_into_parts()
{
	part1="$1"
	part2="$2"
	part3="$3"
}

case "$script_type" in
  up)
	NMSRVRS=""
	SRCHS=""
	for optionvarname in ${!foreign_option_*} ; do
		option="${!optionvarname}"
		echo "$option"
		split_into_parts $option
		if [ "$part1" = "dhcp-option" ] ; then
			if [ "$part2" = "DNS" ] ; then
				NMSRVRS="${NMSRVRS:+$NMSRVRS }$part3"
			elif [ "$part2" = "DOMAIN" ] ; then
				SRCHS="${SRCHS:+$SRCHS }$part3"
			fi
		fi
	done
	R=""
	[ "$SRCHS" ] && R="search $SRCHS
"
	for NS in $NMSRVRS ; do
        	R="${R}nameserver $NS
"
	done
	echo -n "$R" | $resolvConf -a "${dev}.openvpn"
	;;
  down)
	$resolvConf -d "${dev}.openvpn"
	;;
esac

